//In use
export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const GET_EXPANSIONS_LIST = 'GET_EXPANSIONS_LIST'
export const GET_DISPLAYED_CARDS = 'GET_DISPLAYED_CARDS'

//Not in use
export const SET_USER_COLLECTION = 'SET_USER_COLLECTION'
export const SET_DIRTY_FLAG = 'SET_DIRTY_FLAG'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'



