//In use
export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const GET_DISPLAYED_CARDS = 'GET_DISPLAYED_CARDS'
export const SET_EXPANSION_LIST = "SET_EXPANSION_LIST"
export const SET_LOADING = "SET_LOADING"

//Not in use
export const SET_USER_COLLECTION = 'SET_USER_COLLECTION'
export const SET_DIRTY_FLAG = 'SET_DIRTY_FLAG'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'



