//In use
export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const GET_DISPLAYED_CARDS = 'GET_DISPLAYED_CARDS'
export const SET_EXPANSION_LIST = "SET_EXPANSION_LIST"
export const SET_LOADING = "SET_LOADING"
export const SET_REGISTERED = "SET_REGISTERED"
export const CREATE_USER_COLLECTION = "CREATE_USER_COLLECTION"
export const UPDATE_USER_COLLECTION = "UPDATE_USER_COLLECTION"

//Not in use
export const SET_DIRTY_FLAG = 'SET_DIRTY_FLAG'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'



